language: ruby
rvm:
  - 2.4.1

cache: bundler
script:
  - bundle exec jekyll build
  - bundle exec ./validate.rb

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build

cache: bundler # caching bundler gem packages will speed up build

# Optional: disable email notifications about the outcome of your builds
notifications:
  email: false
